common-component
bqaddumi/school-management-system pull request #3
Opened 2021-06-23 15:28 UTC by TaimaTask

2021-06-24 06:14 UTC, IZablah commented on src/commonComponent/SigninSignup.jsx
> +          <label htmlFor="username">Username</label>
please insert HTML Forms

2021-06-24 07:03 UTC, IZablah commented on src/commonComponent/SigninSignup.jsx
> +          name="username"
rename username to email.

2021-06-25 00:40 UTC, bqaddumi requested changes

2021-06-25 00:40 UTC, bqaddumi commented on src/commonComponent/SigninSignup.jsx
> +};
remove and use state or redux if needed

2021-06-25 00:40 UTC, bqaddumi commented on src/commonComponent/SigninSignup.jsx
> +          onChange={(event)=>setPassword(event.target.value)}
move this into new function

2021-06-25 00:40 UTC, bqaddumi commented on src/commonComponent/SigninSignup.jsx
> +export const CommonDataContext = React.createContext(data);
use redux

2021-06-25 00:40 UTC, bqaddumi commented on src/pages/signIn/signinPageForm.jsx
> +    document.getElementById("hideDiv").style.visibility ="visible";
bad practice

2021-06-25 00:40 UTC, bqaddumi commented on src/pages/signIn/signinPageForm.jsx
> +hh();
not good

2021-06-28 14:44 UTC, merged